from __future__ import annotations

from pathlib import Path
from typing import Protocol

from annotation.core.models import (
    AnnotationSet,
    ArtifactRef,
    Dataset,
    ImageAsset,
    LabelSchema,
    ReviewDecision,
)


class MetadataStore(Protocol):
    def save_dataset(self, dataset: Dataset) -> Dataset: ...
    def get_dataset(self, dataset_id: str) -> Dataset | None: ...
    def list_datasets(self) -> list[Dataset]: ...
    def save_asset(self, asset: ImageAsset) -> ImageAsset: ...
    def find_asset_by_checksum(self, dataset_id: str, checksum: str) -> ImageAsset | None: ...
    def list_assets(self, dataset_id: str) -> list[ImageAsset]: ...
    def save_schema(self, schema: LabelSchema) -> LabelSchema: ...
    def get_schema(self, schema_id: str) -> LabelSchema | None: ...
    def save_annotation_set(self, annotation_set: AnnotationSet) -> AnnotationSet: ...
    def get_annotation_set(self, annotation_set_id: str) -> AnnotationSet | None: ...
    def list_annotation_sets(self, dataset_id: str | None = None) -> list[AnnotationSet]: ...
    def save_review_decision(self, decision: ReviewDecision) -> ReviewDecision: ...
    def save_export(self, export_id: str, annotation_set_id: str, payload: dict) -> dict: ...
    def get_export(self, export_id: str) -> dict | None: ...


class ArtifactStore(Protocol):
    def put_file(
        self,
        source_path: Path | str,
        relative_dir: str,
        media_type: str,
        artifact_id: str | None = None,
        copy: bool = True,
    ) -> ArtifactRef: ...

    def write_bytes(
        self,
        relative_path: str,
        data: bytes,
        media_type: str,
        artifact_id: str | None = None,
    ) -> ArtifactRef: ...
