# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['engine.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('tools',        'tools'),
        ('scripts',      'scripts'),
        ('annotation',   'annotation'),
        ('cim_platform', 'cim_platform'),
        ('sheets',       'sheets'),
    ],
    hiddenimports=[
        # management modules (static-seed, not auto-detected by PyInstaller)
        'management_insights',
        'management_oracle_store',
        'management_package_importer',
        'management_schema',
        'management_store',
        'management_use_cases',
        # annotation domain (imported by scripts/*.py data files at runtime)
        'annotation',
        'annotation.adapters',
        'annotation.adapters.coco',
        'annotation.adapters.common',
        'annotation.adapters.isat',
        'annotation.adapters.labeling_runtime',
        'annotation.adapters.labelme',
        'annotation.adapters.xanylabeling',
        'annotation.adapters.xanylabeling_runtime',
        'annotation.adapters.yolo_detection',
        'annotation.adapters.yolo_segmentation',
        'annotation.core',
        'annotation.core.errors',
        'annotation.core.models',
        'annotation.core.states',
        'annotation.core.validation',
        'annotation.domains',
        'annotation.domains.animal',
        'annotation.domains.animal.schema_presets',
        'annotation.formats',
        'annotation.formats.builtins',
        'annotation.formats.contracts',
        'annotation.formats.registry',
        'annotation.integrations',
        'annotation.integrations.connectors',
        'annotation.integrations.connectors.fake_connector',
        'annotation.integrations.connectors.file_connector',
        'annotation.integrations.connectors.rest_connector',
        'annotation.integrations.contracts',
        'annotation.integrations.profiles',
        'annotation.services',
        'annotation.storage',
        'annotation.storage.artifacts',
        'annotation.storage.ports',
        'annotation.storage.sqlite_store',
        'annotation.storage.workspace',
        'annotation.tools',
        'annotation.tools.builtins',
        'annotation.tools.contracts',
        'annotation.tools.registry',
        # platform connector abstraction
        'cim_platform',
        'cim_platform.connector',
        'cim_platform.tenant',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='engine',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
